# Generated by Django 5.2.9 on 2025-12-02 23:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('category', models.CharField(choices=[('TECH', 'Tecnología'), ('GAME', 'Videojuegos'), ('MOVIE', 'Cine y Series'), ('AUDIO', 'Audiófilo')], default='TECH', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(help_text='Puntuación del 1 al 10')),
                ('content', models.TextField(verbose_name='Opinión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
